name: ci
on: [push]
jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly
      - name: Install 📦
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: Start TestRail Run 🏃🏻‍♂️
        run: node ./bin/testrail-run.js

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v2
        with:
          branches: main
        env:
          # github token is automatically created by the GH Action workflow
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # created using semantic-release
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
