name: ci
on: [push]
jobs:
  tests:
    runs-on: ubuntu-20.04
    env:
      # pass TestRail settings from the project secrets
      # via environment variables
      TESTRAIL_HOST: ${{secrets.TESTRAIL_HOST}}
      TESTRAIL_USERNAME: ${{secrets.TESTRAIL_USERNAME}}
      TESTRAIL_PASSWORD: ${{secrets.TESTRAIL_PASSWORD}}
      TESTRAIL_PROJECTID: ${{secrets.TESTRAIL_PROJECTID}}

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly
      - name: Install 📦
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: Start TestRail Run 🏃🏻‍♂️
        id: testRail
        run: |
          runId=$(node ./bin/testrail-start-run.js)
          echo "TestRail run id ${runId}"
          # save the run ID as the output from this step
          echo "::set-output name=runId::${runId}"

      # TODO: run Cypress tests

      - name: Close TestRail Run 🏁
        run: |
          node ./bin/testrail-close-run.js ${{ steps.testRail.outputs.runId }}

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v2
        with:
          branches: main
        env:
          # github token is automatically created by the GH Action workflow
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # created using semantic-release
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
